# Algorithm : Logistic Regression

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# initialize logger
import logging
logging.basicConfig(level = logging.INFO,
                    format = '%(asctime)s - %(levelname)s - %(message)s')

## Dataset Loading

In [2]:
# Read Dataset from file
dataset = pd.read_csv('dataset/train.csv')
logging.info('Dataset Shape : ' + str(dataset.shape) )

2019-01-16 19:29:51,667 - INFO - Dataset Shape : (891, 12)


In [3]:
dataset.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

###  HANDLING MISSING DATA 

In [4]:
cols = dataset.columns
print ("Missing entries in columns : ")
for col in cols:
    missing_entries = dataset[col].isnull().sum()
    if missing_entries > 0:
        print (col)

Missing entries in columns : 
Age
Cabin
Embarked


In [5]:
# Replacing missing values
dataset['Age']=dataset['Age'].fillna(dataset['Age']).median()

### Selecting X and y columns

In [7]:
X = dataset.iloc[:, [2,4,5,6,7,9]].values
y = dataset.iloc[:, 1].values
X[0:3]

array([[3, 'male', 28.0, 1, 0, 7.25],
       [1, 'female', 28.0, 1, 0, 71.2833],
       [3, 'female', 28.0, 0, 0, 7.925]], dtype=object)

In [12]:
X[0:3]

array([[ 1.    ,  3.    , 28.    ,  1.    ,  0.    ,  7.25  ],
       [ 0.    ,  1.    , 28.    ,  1.    ,  0.    , 71.2833],
       [ 0.    ,  3.    , 28.    ,  0.    ,  0.    ,  7.925 ]])

### Handling Categorical Columns

In [9]:
#  HANDLING CATEGORICAL DATA ######################################################################################
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X1 = LabelEncoder()
X[:, 1] = labelencoder_X1.fit_transform(X[:, 1])

In [11]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

# Avoiding the Dummy Variable Trap
X = X[:, 1:]

### Data set split into training and test

In [24]:
#  SPLITTING DATASET INTO TRAIN AND TEST SET ######################################################################################
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

###  Fature Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
logging.info('X_train shape : ' + str(X_train.shape) )
logging.info('X_test shape : ' + str(X_test.shape) )

2019-01-16 19:37:56,893 - INFO - X_train shape : (712, 6)
2019-01-16 19:37:56,894 - INFO - X_test shape : (179, 6)


In [26]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)

In [27]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [28]:
y_pred = classifier.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[95, 15],
       [21, 48]], dtype=int64)